myDjango/devsyns/devsyns/urls.py
import imp
from django.contrib import admin
from django.urls import path
import account
from devapp import views
from account import views as account_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('postcreate/', views.postcreate, name='postcreate'),
    path('detail/<int:post_id>', views.detail, name='detail'),
    path('new_comment/<int:post_id>', views.new_comment, name='new_comment'),
    path('login/', account_views.login, name='login'),
    path('logout/', account_views.logout, name='logout'),
    path('freehome', views.freehome, name='freehome'),
    path('freepostcreate/', views.freepostcreate, name='freepostcreate'),
    path('freedetail/<int:post_id>', views.freedetail, name='freedetail'),
    path('new_freecomment/<int:post_id>', views.new_freecomment, name='new_freecomment'),
    path('sign_up/', account_views.sign_up, name='sign_up'),
]

myDjango/devsyns/account/models.py
from django.db import models

# Create your models here.

myDjango/devsyns/devapp/models.py
from tkinter import CASCADE
from django.db import models
from django.contrib.auth.models import User

# 게시물 모델
class Post(models.Model):
    title = models.CharField(max_length=200)
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

class Comment(models.Model):
    comment = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(Post, null=True, blank=True, on_delete=models.CASCADE )

    def __str__(self):
        return self.comment

class FreePost(models.Model):
    title = models.CharField(max_length=200)
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class FreeComment(models.Model):
    comment = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(FreePost, null=True, blank=True, on_delete=models.CASCADE )

    def __str__(self):
        return self.comment

myDjango/devsyns/devapp/forms.py
from dataclasses import field
from xml.etree.ElementTree import Comment
from django import forms
from .models import Post,Comment, FreePost, FreeComment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'
    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)

        self.fields['title'].widget.attrs = {
            'class': 'form-control',
            'placeholder': "글 제목을 입력해주세요",
            'rows': 20
        }
        self.fields['body'].widget.attrs = {
            'class':'form-control',
            'placeholder': '글 제목을 입력해주세요',
            'rows': 20,
            'cols' : 100
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment']
    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
    
        self.fields['comment'].widget.attrs = {
                'class':'form-control',
                'placeholder': '댓글을 입력해주세요',
                'rows': 10
            }

class FreePostForm(forms.ModelForm):
    class Meta:
        model = FreePost
        fields = ['title', 'body']
    def __init__(self, *args, **kwargs):
        super(FreePostForm, self).__init__(*args, **kwargs)

        self.fields['title'].widget.attrs = {
            'class': 'form-control',
            'placeholder': "글 제목을 입력해주세요",
            'rows': 20
        }
        self.fields['body'].widget.attrs = {
            'class':'form-control',
            'placeholder': '글 제목을 입력해주세요',
            'rows': 20,
            'cols' : 100
        }


class FreeCommentForm(forms.ModelForm):
    class Meta:
        model = FreeComment
        fields = ['comment']
    def __init__(self, *args, **kwargs):
        super(FreeCommentForm, self).__init__(*args, **kwargs)
    
        self.fields['comment'].widget.attrs = {
                'class':'form-control',
                'placeholder': '댓글을 입력해주세요',
                'rows': 10
            }

myDjango/devsyns/account/views.py
from django.shortcuts import redirect, render
from django.contrib import auth
from django.contrib.auth.models import User

def login(req):
    if req.method == 'POST':
        username = req.POST['username']
        password = req.POST['password']
        user= auth.authenticate(req, username=username, password=password)
        if user is not None:
            auth.login(req, user)
            return redirect('home')
        else:
            return render(req, 'bad_login.html')
    else:
        return render(req, 'login.html')

def logout(req):
    auth.logout(req)
    return redirect('home')

def sign_up(req):
    if req.method == 'POST':
        if req.POST['password'] == req.POST['repeat']:
            new_user = User.objects.create_user(username=req.POST['username'], password=req.POST['password'])
            auth.login(req, new_user)
            return redirect('home')
    return render(req, 'register.html')

myDjango/devsyns/devapp/views.py
from django.shortcuts import redirect, render, get_object_or_404
from devapp.forms import PostForm
from .forms import PostForm, CommentForm, FreeCommentForm, FreePostForm
from .models import Post, FreePost

# Create your views here.
def home(req):
    # posts = Post.objects.all()
    posts = Post.objects.filter().order_by('-date')
    return render(req, 'index.html', {'posts': posts})

def postcreate(req):
    if req.method == 'POST' or req.method == 'FILES':
        form = PostForm(req.POST, req.FILES)
        if form.is_valid:
            form.save()
        return redirect('home')
    else:
        form = PostForm()
        return render(req, 'post_form.html', {'form' : form})

def detail(req, post_id):
    post_detail = get_object_or_404(Post, pk=post_id)
    comment_form = CommentForm()
    return render(req, 'detail.html', {'post_detail': post_detail, 'comment_form' : comment_form})

def new_comment(req, post_id):
    field_form = CommentForm(req.POST)
    if field_form.is_valid:
        form = field_form.save(commit=False)
        form.post = get_object_or_404(Post, pk=post_id)
        form.save()
    return redirect('detail',post_id)


# FREE============================================================

def freehome(req):
    # posts = Post.objects.all()
    posts = FreePost.objects.filter().order_by('-date')
    return render(req, 'free_index.html', {'posts': posts})

def freepostcreate(req):
    if req.method == 'POST' or req.method == 'FILES':
        form = FreePostForm(req.POST, req.FILES)
        if form.is_valid:
            unfinished = form.save(commit=False)
            unfinished.author = req.user
            unfinished.save()
        return redirect('freehome')
    else:
        form = FreePostForm()
        return render(req, 'free_post_form.html', {'form' : form})

def freedetail(req, post_id):
    post_detail = get_object_or_404(FreePost, pk=post_id)
    comment_form = FreeCommentForm()
    return render(req, 'freedetail.html', {'post_detail': post_detail, 'comment_form' : comment_form})

def new_freecomment(req, post_id):
    field_form = FreeCommentForm(req.POST)
    if field_form.is_valid:
        form = field_form.save(commit=False)
        form.post = get_object_or_404(FreePost, pk=post_id)
        form.save()
    return redirect('freedetail',post_id)

myDjango/devsyns/account/templates/bad_login.html
존재하지 않는 회원입니다 다시 로그인 해주세요
<br>
<a href="{% url 'login' %}">다시 로그인 하기</a>

myDjango/devsyns/account/templates/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Login</title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>
                                    </div>
                                    <form method="post" class="user">
                                        {% csrf_token %}
                                        <div class="form-group">
                                            <input type="text" class="form-control form-control-user"
                                                id="username" name="username"placeholder="Enter Your ID">
                                        </div>
                                        <div class="form-group">
                                            <input type="password" class="form-control form-control-user"
                                                id="password" name="password" placeholder="Password">
                                        </div>
                                        <!-- <a href="#" class="btn btn-primary btn-user btn-block">
                                            Login
                                        </a> -->
                                        <input type="submit" class="btn btn-primary btn-user btn-block" value="Login">
                                        <hr>
                                    </form>
                                    <div class="text-center">
                                        <a class="small" href="{% url 'sign_up' %}">Create an Account!</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

</body>

</html>

myDjango/devsyns/account/templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Register</title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

    <div class="container">

        <div class="card o-hidden border-0 shadow-lg my-5">
            <div class="card-body p-0">
                <!-- Nested Row within Card Body -->
                <div class="row">
                    <div class="col-lg-5 d-none d-lg-block bg-register-image"></div>
                    <div class="col-lg-7">
                        <div class="p-5">
                            <div class="text-center">
                                <h1 class="h4 text-gray-900 mb-4">Create an Account!</h1>
                            </div>
                            <form class="user" method="post">
                                {% csrf_token%}
                                <div class="form-group">
                                    <input type="text" name="username" class="form-control form-control-user" id="exampleInputEmail"
                                        placeholder="Id">
                                </div>
                                <div class="form-group row">
                                    <div class="col-sm-6 mb-3 mb-sm-0">
                                        <input type="password" name="password" class="form-control form-control-user"
                                            id="exampleInputPassword" placeholder="Password">
                                    </div>
                                    <div class="col-sm-6">
                                        <input type="password" name="repeat" class="form-control form-control-user"
                                            id="exampleRepeatPassword" placeholder="Repeat Password">
                                    </div>
                                </div>
                                <input type="submit" class="btn btn-primary btn-user btn-block" value="회원가입">
                            </form>
                            <hr>
                            <div class="text-center">
                                <a class="small" href="{% url 'login' %}">Already have an account? Login!</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

</body>

</html>

myDjango/devsyns/devapp/templates/detail.html
{% extends 'base.html' %}
{% block content %}
상세 페이지
<h1>제목 : {{post_detail.title}}</h1>
<h2>작성 날짜 : {{post_detail.date}}</h2>
<p>
    {{post_detail.body}}
</p>

<!-- 댓글 출력 공간 -->
{% for comment in post_detail.comment_set.all %}
    <p>{{comment.comment}}</p>
    <p>{{comment.date}}</p>
    <br>
{% endfor %}

<!--  댓글 입력 공간 -->
<form action="{% url 'new_comment' post_detail.id %}" method="post">
    {% csrf_token %}
    {{ comment_form}}
    <input type="submit" value="댓글 입력">
</form>

{% endblock %}

myDjango/devsyns/devapp/templates/forgot-password.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Forgot Password</title>

    <!-- Custom fonts for this template-->
    <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="css/sb-admin-2.min.css" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-block bg-password-image"></div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-2">Forgot Your Password?</h1>
                                        <p class="mb-4">We get it, stuff happens. Just enter your email address below
                                            and we'll send you a link to reset your password!</p>
                                    </div>
                                    <form class="user">
                                        <div class="form-group">
                                            <input type="email" class="form-control form-control-user"
                                                id="exampleInputEmail" aria-describedby="emailHelp"
                                                placeholder="Enter Email Address...">
                                        </div>
                                        <a href="login.html" class="btn btn-primary btn-user btn-block">
                                            Reset Password
                                        </a>
                                    </form>
                                    <hr>
                                    <div class="text-center">
                                        <a class="small" href="register.html">Create an Account!</a>
                                    </div>
                                    <div class="text-center">
                                        <a class="small" href="login.html">Already have an account? Login!</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="js/sb-admin-2.min.js"></script>

</body>

</html>

myDjango/devsyns/devapp/templates/free_index.html
{% extends 'base.html'%}
{% block content %}
<!-- Page Heading -->
<h1 class="h3 mb-2 text-gray-800">자유게시판</h1>
<!-- DataTales Example -->
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">DataTables Example</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th style="width: 60%">글 제목</th>
                        <th>작성 날짜</th>
                        <th>작성자</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Tiger Nixon</td>
                        <td>2011/04/25</td>
                        <td>Edinburgh</td>
                    </tr>
                    {% for post in posts %}
                    <tr>
                        <td><a href="{% url 'freedetail' post.id %}">{{post.title}}</a></td>
                        <td>{{post.date}}</td>
                        <td>{{post.author.username}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% if user.is_authenticated %}
<a href="{% url 'freepostcreate' %}" class="btn btn-primary btn-icon-split">
    <span class="icon text-white-50">
        <i class="fas fa-flag"></i>
    </span>
    <span class="text">글쓰기</span>
</a>
{% endif %}

{% endblock %}

myDjango/devsyns/devapp/templates/free_post_form.html
{% extends 'base.html' %}
{% block content %}
<h1>새 글 작성</h1>
<form action="#" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
    {{ form.as_p }}
    </table>
    <input type="submit" value="새 글">
</form>
{% endblock %}

myDjango/devsyns/devapp/templates/freedetail.html
{% extends 'base.html' %}
{% block content %}
상세 페이지
<h1>제목 : {{post_detail.title}}</h1>
<p>작성 날짜 : {{post_detail.date}}</p>
<p>{{post_detail.author.username}}</p>
<p>
    {{post_detail.body}}
</p>

<!-- 댓글 출력 공간 -->
{% for comment in post_detail.freecomment_set.all %}
    <p>{{comment.comment}}</p>
    <p>{{comment.date}}</p>
    <br>
{% endfor %}

<!--  댓글 입력 공간 -->
<form action="{% url 'new_freecomment' post_detail.id %}" method="post">
    {% csrf_token %}
    {{ comment_form}}
    <input type="submit" value="댓글 입력">
</form>

{% endblock %}

myDjango/devsyns/devapp/templates/index.html
{% extends 'base.html'%}
{% block content %}
<!-- Page Heading -->
<h1 class="h3 mb-2 text-gray-800">자유게시판</h1>
<!-- DataTales Example -->
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">DataTables Example</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th style="width: 60%">글 제목</th>
                        <th>작성 날짜</th>
                        <th>작성자</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Tiger Nixon</td>
                        <td>2011/04/25</td>
                        <td>Edinburgh</td>
                    </tr>
                    {% for post in posts %}
                    <tr>
                        <td><a href="{% url 'detail' post.id %}">{{post.title}}</a></td>
                        <td>{{post.date}}</td>
                        <!-- <td>{{post.author}}</td> -->
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
<a href="{% url 'postcreate' %}" class="btn btn-primary btn-icon-split">
    <span class="icon text-white-50">
        <i class="fas fa-flag"></i>
    </span>
    <span class="text">글쓰기</span>
</a>

{% endblock %}

myDjango/devsyns/devapp/templates/post_form.html
{% extends 'base.html' %}
{% block content %}
<h1>새 글 작성</h1>
<form action="#" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="새 글">
</form>
{% endblock %}